@set $boost_root=d:\boost_1_66_0
@set adsk_clm_wpad_proxy_check=false
@set allusersprofile=c:\programdata
@set appdata=c:\users\dima\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-vd0h10d
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set facades_4.5=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.5\facades
@set facades_4.5.1=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.5.1\facades
@set facades_4.5.2=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.5.2\facades
@set facades_4.6=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.6\facades
@set facades_4.6.1=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.6.1\facades
@set facades_4.7.1=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.7.1\facades
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft sdks\f#\10.1\framework\v4.0\
@set homedrive=c:
@set homepath=\users\dima
@set htmlhelpdir=c:\program files (x86)\html help workshop
@set ifcpath=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\ifc\x86
@set include=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\shared;c:\program files (x86)\windows kits\10\include\10.0.17134.0\um;c:\program files (x86)\windows kits\10\include\10.0.17134.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt
@set intel_dev_redist=c:\program files (x86)\common files\intel\shared libraries\
@set java_home=c:\program files\java\jdk-9.0.4
@set kmp_duplicate_lib_ok=true
@set lib=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\lib\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.17134.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.17134.0\um\x86
@set libpath=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\lib\x86;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.17134.0;c:\program files (x86)\windows kits\10\references\10.0.17134.0;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\dima\appdata\local
@set logonserver=\\desktop-vd0h10d
@set m2_home=c:\program files\apache-maven-3.5.2
@set maven_home=c:\program files\apache-maven-3.5.2
@set mic_ld_library_path=c:\program files (x86)\common files\intel\shared libraries\compiler\lib\intel64_win_mic
@set mkl_serial=yes
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\microsoft visual studio\2017\community\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=2
@set onedrive=c:\users\dima\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\bin\hostx86\x86;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft sdks\typescript\2.8;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\community\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft sdks\f#\10.1\framework\v4.0\;c:\program files (x86)\windows kits\10\bin\10.0.17134.0\x86;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\microsoft visual studio\2017\community\\msbuild\15.0\bin;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\github\github\lib\win32\x86;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\git\cmd;c:\program files\apache-maven-3.5.2\bin;c:\program files\nodejs\;$boost_root\bin;c:\program files\dotnet\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\nvidia corporation\physx\common;c:\users\dima\appdata\local\programs\python\python36-32\scripts\;c:\users\dima\appdata\local\programs\python\python36-32\;c:\users\dima\appdata\local\microsoft\windowsapps;c:\users\dima\appdata\local\githubdesktop\bin;c:\program files\apache-maven-3.5.2\bin;c:\users\dima\appdata\roaming\npm;d:\microsoft vs code\bin;c:\users\dima\appdata\local\atom\bin;c:\program files (x86)\adb
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\dima\appdata\local\microsoft\visualstudio\15.0_33ee172f\devenv.exe.config
@set platform=x86
@set processor_architecture=amd64
@set processor_identifier=amd64 family 16 model 6 stepping 2, authenticamd
@set processor_level=16
@set processor_revision=0602
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\dima\appdata\local\temp
@set tmp=c:\users\dima\appdata\local\temp
@set ucrtversion=10.0.17134.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-vd0h10d
@set userdomain_roamingprofile=desktop-vd0h10d
@set username=dima
@set userprofile=c:\users\dima
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2017\community\vc\redist\msvc\14.14.26405\
@set vctoolsversion=14.14.26428
@set visualstudiodir=c:\users\dima\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio community 2017
@set visualstudioversion=15.0
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=15.7.1
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\
@set vslang=1033
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.17134.0;c:\program files (x86)\windows kits\10\references\10.0.17134.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.17134.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.17134.0\
@set windowssdkversion=10.0.17134.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\github\github\lib\win32\x86;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\git\cmd;c:\program files\apache-maven-3.5.2\bin;c:\program files\nodejs\;$boost_root\bin;c:\program files\dotnet\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\nvidia corporation\physx\common;c:\users\dima\appdata\local\programs\python\python36-32\scripts\;c:\users\dima\appdata\local\programs\python\python36-32\;c:\users\dima\appdata\local\microsoft\windowsapps;c:\users\dima\appdata\local\githubdesktop\bin;c:\program files\apache-maven-3.5.2\bin;c:\users\dima\appdata\roaming\npm;d:\microsoft vs code\bin;c:\users\dima\appdata\local\atom\bin;c:\program files (x86)\adb

@call "cl.exe" @"D:\stud-textrpg\MapCreator.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1